-- Jalankan seluruh skrip ini di Supabase SQL Editor.
create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date timestamptz not null default now(),
    category text not null,
    "subCategory" text not null,
    amount bigint not null default 0,
    profit bigint not null default 0,
    "sellPrice" bigint,
    customer text,
    source text,
    destination text,
    "adminFeeMethod" text,
    account text,
    description text
);

create table if not exists public.balances (
    date date not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    balances jsonb not null default '{}'::jsonb,
    primary key (user_id, date)
);

alter table public.transactions enable row level security;
alter table public.balances enable row level security;

drop policy if exists "Users can manage their transactions" on public.transactions;
create policy "Users can manage their transactions"
    on public.transactions for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Users can manage their balances" on public.balances;
create policy "Users can manage their balances"
    on public.balances for all to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create index if not exists transactions_user_date_idx
    on public.transactions (user_id, date);
